export const TOGGLE_SAVE_BEER_MUTATION = 'TOGGLE_SAVE_BEER_MUTATION'
export const SET_BEERS_MUTATION = 'SET_BEERS_MUTATION'
export const TOGGLE_SAVE_BEER_ACTION = 'TOGGLE_SAVE_BEER_ACTION'
export const SET_BEERS_ACTION = 'SET_BEERS_ACTION'